# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Ballerina.Ballerina
PackageVersion: 2201.10.0
PackageLocale: en-US
Publisher: WSO2
PublisherUrl: https://wso2.com
PrivacyUrl: https://ballerina.io/privacy-policy
PackageName: Ballerina
PackageUrl: https://ballerina.io
License: Apache License 2.0
LicenseUrl: https://github.com/ballerina-platform/ballerina-lang/blob/master/LICENSE
CopyrightUrl: https://github.com/ballerina-platform/ballerina-lang/blob/master/COPYRIGHT
ShortDescription: Ballerina is an open-source cloud-native programming language optimized for integration. It is developed and supported by WSO2.
Description: Ballerina is an open-source cloud-native programming language optimized for integration. It is developed and supported by WSO2. With Ballerina, you could easily develop microservices, API endpoints and integrations, and any other application for the cloud. Additionally, Ballerina has all the general-purpose functionalities you could expect from a modern programming language. With Ballerina's compiler-level built-in support for widely used data types such as JSON and XML, your focus on handling structured data, network service interactions, and dealing with concurrency is made much more effective.
ReleaseNotesUrl: https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.10.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
